parameters:
  doctrine.connection.name: 'doctrine'
  doctrine.database.name: 'doctrine'
  doctrine.entity.map.file: 'entitymap'
  doctrine.entity.map.extension: '.orm.yml'

services:
  doctrine.entity.manager:
    class: Doctrine\ORM\EntityManager
    factory: ['@doctrine.entity.manager.factory', 'create']
    arguments:
      - '@database.mvcc'
      - '@doctrine.config'
      - '@doctrine.event.manager'
      - '@time.factory'
  doctrine.config:
    class: Doctrine\ORM\Configuration
    factory: ['@doctrine.config.factory', getConfiguration]
    arguments:
      - '@doctrine.cache'
      - '%app.env%'
      - '%app.dir%/%app.config.dir%'
      - '%doctrine.entity.map.file%'
      - '%doctrine.entity.map.extension%'
  doctrine.config.factory:
    class: Vain\Doctrine\Factory\DoctrineConfigurationFactory
  doctrine.event.manager:
    class: Vain\Doctrine\Event\Manager\DoctrineEventManager
    arguments: ['@time.factory']
  connection.factory.doctrine:
    class: Vain\Doctrine\Connection\Factory\DoctrineConnectionFactory
    arguments: ['doctrine.pdo', '@connection.factory.pdo']
    tags:
      - {name: connection.factory}
  doctrine.connection.pdo:
    class: PDOConnection
    factory: ['@connection.storage', getConnection]
    arguments:
      - '%doctrine.connection.name%'
  database.factory.doctrine:
    class: Vain\Doctrine\Database\Factory\DoctrineDatabaseFactory
    arguments: ['@doctrine.config', '@doctrine.event.manager', '@database.generator.factory', '%doctrine.database.name%']
    tags:
      - {name: database.factory}
  doctrine.cache.memory:
    class: Doctrine\Common\Cache\ArrayCache
  doctrine.cache.apcu:
    class: Vain\Doctrine\Cache\Apcu\DoctrineApcuCache
  doctrine.cache.redis:
    class: Vain\Doctrine\Cache\Redis\DoctrineRedisCache
    arguments: ['@app.cache.redis']
  doctrine.entity.manager.factory:
    class: Vain\Doctrine\Factory\DoctrineEntityManagerFactory
  entity.operation.factory.doctrine:
    parent: entity.operation.factory.abstract
    class: Vain\Doctrine\Entity\Operation\Factory\DoctrineEntityOperationFactory
    arguments: ['@doctrine.entity.manager']
  operation.collection.factory.doctrine:
    class: Vain\Doctrine\Operation\Collection\Factory\Decorator\DoctrineCollectionFactoryDecorator
    decorates: operation.collection.factory
    decoration_priority: 300
    arguments: ['@operation.collection.factory.doctrine.inner', '@doctrine.entity.manager']
  doctrine.event.handler:
    parent: event.handler.abstract
    class: Vain\Doctrine\Event\DoctrineEventHandler
    arguments: ['@doctrine.entity.manager']