imports:
  - { resource: '../di.yml' }

services:
  connection.factory.doctrine.assert:
    class: Vain\Connection\Factory\Decorator\Assert\ConnectionFactoryAssertDecorator
    decorates: connection.factory.doctrine
    arguments: ['@connection.factory.doctrine.assert.inner', '%doctrine.config.required.fields%']
