imports:
  - { resource: '../di.yml' }

parameters:
  doctrine.config.required.fields: []

services:
  connection.factory.doctrine.assert:
    class: Vain\Connection\Factory\Decorator\Assert\ConnectionFactoryAssertDecorator
    decorates: connection.factory.doctrine
    decoration_priority: 900
    arguments: ['@connection.factory.doctrine.assert.inner', '%doctrine.config.required.fields%']
  connection.factory.doctrine.logger:
    class: Vain\Connection\Factory\Decorator\Logger\ConnectionFactoryLoggerDecorator
    decorates: connection.factory.doctrine
    decoration_priority: 1000
    arguments: ['@connection.factory.doctrine.logger.inner', '@logger.connection']